language: c

compiler:
    - gcc

before_install:
    - sudo add-apt-repository --yes ppa:vala-team
    - sudo apt-get update --quiet
    - sudo apt-get install --yes --force-yes valac-0.26 libglib2.0-bin
      libglib2.0-dev libsoup2.4-dev libgee-0.8-dev libfcgi-dev libjson-glib-dev
      libmemcached-dev libluajit-5.1-dev libctpl-dev python-pip
    - sudo pip install cpp-coveralls sphinx PyYAML

before_script:
    - ./waf configure --enable-gcov --prefix=/usr
    - ./waf build
    - sudo ./waf install

script:
    - build/tests/tests
    - sphinx-build docs build/docs

after_success:
    - coveralls --repo-token $COVERALLS_TOKEN --build-root build
                --exclude build/examples --exclude build/tests
