site_name: My Docs
repo_url: https://github.com/antono/valum
theme: readthedocs
pages:
    - [index.md, Valum]
    - [server/soup.md, Server, Soup]
    - [server/fastcgi.md, Server, FastCGI]
    - [about/gnu-lgpl-v3.0.md, About, License]
