site_name: Valum
repo_url: https://github.com/antono/valum
theme: readthedocs
pages:
    - [index.md, Valum]
    - [route.md, Route]
    - [server/soup.md, Server, Soup]
    - [server/fastcgi.md, Server, FastCGI]
    - [about/gnu-lgpl-v3.0.md, About, License]
