site_name: Valum
repo_url: https://github.com/antono/valum
theme: readthedocs
pages:
    - [index.md, Valum]
    - [installation.md, Installation]
    - [getting-started.md, Getting started]
    - [application.md, Basics, Application]
    - [vsgi/request.md, Basics, Request]
    - [vsgi/response.md, Basics, Response]
    - [redirection-and-error.md, Basics, Redirection and Error]
    - [route.md, Basics, Route]
    - [router.md, Basics, Router]
    - [server/soup.md, Server, Soup]
    - [server/fastcgi.md, Server, FastCGI]
    - [module.md, Extra, Modular Application]
    - [ctpl.md, Extra, CTPL]
    - [scripting.md, Extra, Scripting]
    - [about/gnu-lgpl-v3.0.md, About, License]

