site_name: Valum
repo_url: https://github.com/antono/valum
theme: readthedocs
pages:
    - [index.md, Valum]
    - [router.md, Basics, Router]
    - [route.md, Basics, Route]
    - [about/gnu-lgpl-v3.0.md, About, License]
